@startuml

[*] --> ログイン
ログイン : ログイン
ログイン : ゲストログイン
ログイン : 新規登録
ログイン --> 新規登録
ログイン --> トップ

新規登録 : ID入力フォーム
新規登録 : パスワード入力フォーム
新規登録 : 登録してログイン
新規登録 --> トップ

トップ : ファイルのアップロード
トップ : OCRが抽出したテキストの表示・編集
トップ : テキストの送信
トップ : アカウント設定(ログイン中のみ)
トップ : 履歴一覧(ログイン中のみ)
トップ : ログアウト(ログイン中のみ)
トップ --> リザルト
トップ --> アカウント設定
トップ --> 履歴一覧
トップ --> ログイン

リザルト : ChatGPTの返信結果
リザルト --> トップ

アカウント設定 : IDの変更
アカウント設定 : パスワードの変更
アカウント設定 : アカウントの削除
アカウント設定 --> トップ

履歴一覧 : 履歴
履歴一覧 --> トップ
履歴一覧 --> 履歴詳細

履歴詳細 : ChatGPTの返信結果
履歴詳細 --> トップ

@enduml
