@startuml

[*] --> ログイン画面
ログイン画面 : ログイン
ログイン画面 : ゲストログイン
ログイン画面 : 新規登録
ログイン画面 --> 新規登録画面 : 新規登録
ログイン画面 --> TOP画面 : ログイン

新規登録画面 : ID入力フォーム
新規登録画面 : パスワード入力フォーム
新規登録画面 --> TOP画面 : 登録してログイン

TOP画面 : 画像ファイルをアップロード
TOP画面 : ChatGPTに説明を依頼
TOP画面 : 履歴
TOP画面 --> 履歴画面 : 履歴

履歴画面 : 履歴データ
履歴画面 --> 履歴データ : 履歴データ

@enduml
